### ISSUE TITLE
Error on completion when using import as

### ISSUE THREAD

**Issue by tj12961** [syohex/emacs-company-jedi#10]
I have installed company-jedi and the relevant python packages and for simple scripts, the completion works perfectly.

In various scripts where the imported package name is long, I like to use import as for example:

    import matplotlib.pyplot as plt

When I do this, on typing 'plt.' I am presented with the error in the epc buffer as:
'ERROR:epc:KeyError(<Name: deprecate@244,11>,)'

Apologies if I am being stupid.

**Comment by syohex** [comment]
Thanks for reporting. I suppose this issue might be fixed by https://github.com/tkf/emacs-jedi/pull/252. Please update(You need wait some hours until MELPA update) and try again.

![company-jedi](https://cloud.githubusercontent.com/assets/554281/10748324/4e9009d0-7ca2-11e5-8679-8ffdc9e17755.png)

**Comment by syohex** [comment]
I confirmed MELPA update.

**Comment by syohex** [comment]
Please reopen if you still have problem.
