### ISSUE TITLE
Fresh install with issues. 

### ISSUE THREAD

**Issue by fxfactorial** [syohex/emacs-company-jedi#11]
Two small issues. 

1) For a reason that I haven't looked into, installing company-jedi via package-install does not download the dependency of jedi-core. 
2) Once installed I have (company-mode)(company-jedi) called for the python mode hook, but I get this error: 

```lisp
File mode specification error: (wrong-number-of-arguments ((t) (command &optional arg &rest ignored) "`company-mode' completion back-end for `jedi-code.el'.
Provide completion info according to COMMAND and ARG.  IGNORED, not used." (interactive (list (quote interactive))) (cond ((eql command (quote interactive)) (company-begin-backend (quote company-jedi))) ((eql command (quote prefix)) (and (derived-mode-p (quote python-mode)) (not (company-in-string-or-comment)) (or (company-jedi-prefix) (quote stop)))) ((eql command (quote candidates)) (cons :async (quote company-jedi-candidates))) ((eql command (quote meta)) (company-jedi-meta arg)) ((eql command (quote annotation)) (company-jedi-annotation arg)) ((eql command (quote doc-buffer)) (company-jedi-doc-buffer arg)) ((eql command (quote location)) nil) ((eql command (quote sorted)) t))) 0)
```

**Comment by syohex** [comment]
> 1) For a reason that I haven't looked into, installing company-jedi via package-install does not download the dependency of jedi-core. 

I cannot reproduce.

> 2) Once installed I have (company-mode)(company-jedi) called for the python mode hook, but I get this error:

Your configuration is incorrect. You should not call `company-jedi` in the hook and should set `company-backends` setting in python-mode hook as below.

```lisp
(defun my/python-mode-hook ()
  (company-mode +1)
  (add-to-list 'company-backends 'company-jedi))

(add-hook 'python-mode-hook 'my/python-mode-hook)
```

BTW: You should enable global-company-mode if you want to use company-mode in any buffers.

**Comment by fxfactorial** [comment]
@syohex 

Regarding 2, It seems like it works off the bat with python2, but for python3 do you provide a higher abstraction than just do `(setq jedi:server-args '("--sys-path"...")`, 

Also, how can I turn on the doc strings popups, like the auto-complete based jedi does.

**Comment by syohex** [comment]
> Also, how can I turn on the doc strings popups, like the auto-complete based jedi does.

Install [company-quickhelp](https://github.com/expez/company-quickhelp) and enable `company-quickhelp-mode`.

**Comment by fxfactorial** [comment]
Excellent, thank you.
