### ISSUE TITLE
Incompatibility with company-quickhelp

### ISSUE THREAD

**Issue by yusekiya** [syohex/emacs-company-jedi#13]
I've intalled `company-jedi`, `company`, `company-quickhelp`, and `pos-tip` from melpa.
Auto completion and displaying quickhelp are working well.
However, soon after `company-quickhelp` displays a tooltip, the tooltip hides,
and instead a tooltip for function arguments is displayed if the cursor is on the function.
I guess the cause is that `jedi:tooltip-show` is invoked while `company-quickhelp` is displaying the tooltip.

Would you please disable `jedi:tooltip-show` when `company-quickhelp` is displaying the tooltip?

**Comment by syohex** [comment]
Please set `nil` to `jedi:tooltip-method` and try again.

**Comment by yusekiya** [comment]
Thank you very much for your prompt reply!

I've followed your advice.
The behavior of the tooltip gets better but it is a little bit different from what I want to do.
I want display tooltip for function arguments by using pos-tip unless company-quickhelp is displaying tooltips.

To clarify this, let me give an example

```python
import sys

print()
print(sys.)
```

If the cursor is in the parentheses of the first print function, I want to display tooltip for the arguments of `print()` by using pos-tip.
If the cursor is at just after `sys.` in the second print function, and `company-quickhelp` is displaying
a tooltip for a possible completions of `sys.`, I want `jedi:tooltip-show` not to show the tooltip for the print function.

**Comment by syohex** [comment]
@yusekiya Could you upgrade jedi-core and try again ?

See
- https://github.com/tkf/emacs-jedi/pull/257

**Comment by yusekiya** [comment]
Yeah! it works now
Thank you :)
