### ISSUE TITLE
Support for type hints?

### ISSUE THREAD

**Issue by LQYMGT** [syohex/emacs-company-jedi#14]
I'm not very sure, but it seems that YouCompleteMe(vim) uses jedi too? And it can autocomplete for the following code:
```python
def test(s: str):
    s. # autocomplete here
```

but company-jedi can't.

**Comment by syohex** [comment]
I suppose jedi does not support Python 3.5 type hinting yet.

**Comment by LQYMGT** [comment]
I just installed YouCompleteMe for vim, and below is a example:

![2016-01-30-192944_1366x768_scrot](https://cloud.githubusercontent.com/assets/7553512/12695402/f3533674-c787-11e5-896d-b0f2b2948157.png)

And [here](https://github.com/Valloric/YouCompleteMe#intro) says it's based on jedi.

**Comment by syohex** [comment]
Sorry I confused type annotation and type hinting. It is type annotation. I heard from python hacker that Jedi supports it.

![jedi](https://cloud.githubusercontent.com/assets/554281/12696306/8c7144dc-c7aa-11e5-84de-76779eb2cce4.png)

However I cannot get candidates as above screenshot. I cannot understand how YouCompleteMe gets candidates ?

**Comment by syohex** [comment]
Jedi supports it only Python 2. I confirmed company-jedi works it with python 2.

![jedi2](https://cloud.githubusercontent.com/assets/554281/12699416/85b5e32a-c7fd-11e5-9c42-5d210458b6a5.png)

Please use Python 2. (YouCompleteMe use Python2 when both Python2 and Python3 are available.)

**Comment by LQYMGT** [comment]
Sorry, but how to configure it to use Python2?

**Comment by syohex** [comment]
Set jedi:environment-virtualenv to use python2 virtualenv and `jedi:install-server`.

```lisp
(custom-set-variables
 '(jedi:environment-virtualenv
   '("/usr/bin/virtualenv" "--system-site-packages"))) ;; Specify Python2 virtualenv path
```

Or prepend Python2 path ahead of Python3 path.

**Comment by LQYMGT** [comment]
Works fine now. Thanks a lot.
