### ISSUE TITLE
How to setup jedi to recognise user package and auto complete them

### ISSUE THREAD

**Issue by luluman** [syohex/emacs-company-jedi#15]
I'm using company-mode and company-jedi, they both work good when complete the package provide by the system (sit-packages). Although when I import the class written by myself, company does not complete it for me and shows `deferred error : (error "\"AttributeError(\\\"'ValueError' object has no attribute 'message'\\\",)\"")`. I have tested python in the terminal and the path was right configured. I don't know how to configure jedi in the right way to make it aware user path and auto complete it.

**Comment by syohex** [comment]
Could you tell me your jedi(Python package) version ? And if you use older version. please upgrade and try again.

**Comment by luluman** [comment]
The jedi version is 0.9.0. It's the latest form now on. Although I don't know how jedi works, I find it active a process of python which is located in `/Users/LuluMan/.emacs.d/.python-environments/default/bin/python3.5`(in my computer). Also, I have checked this process and got this: `/Users/LuluMan/.emacs.d/.python-environments/default/bin/python3.5
Python 3.5.1 (default, Dec 11 2015, 00:55:02) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import arcsar as ac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/LuluMan/Documents/Python/UserLib/arcsar.py", line 8, in <module>
    import matplotlib.pylab as plt
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pylab.py", line 274, in <module>
    from matplotlib.pyplot import *
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
>>> 
` May that is the reason why jedi can't complete my own package. But I can't figure out how to solve it.

**Comment by syohex** [comment]
```
(error "\"AttributeError(\\\"'ValueError' object has no attribute 'message'\\\",)\"").
```

Could you show me minimal code for reproducing this issue ?


> RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ

This is your environment issue. Please set matplotlib backend correctly.
Add following code to `~/.matplotlib/matplotlibrc`
```
backend: TkAgg
```

References
- http://stackoverflow.com/questions/4130355/python-matplotlib-framework-under-macosx

**Comment by luluman** [comment]
> This is your environment issue. Please set matplotlib backend correctly.
Add following code to ~/.matplotlib/matplotlibrc
`backend: TkAgg`

This really show the "RuntimeError: " problem, but not jedi. 
>Could you show me minimal code for reproducing this issue ?

1. I have some python packages which I put them in "/Users/xxx/Documents/Python/UserLib";
2. I put a file named "xx.pth" included string '/Users/xxx/Documents/Python/UserLib' in /usr/local/lib/python3.5/site-packages; and ipython will include my package path to the sys.path when I use emacs and terminal.
3. I use "import arcsar as ac"(arcsar.py is in "/Users/xxx/Documents/Python/UserLib") and type "ac." waiting jedi to give me some completion. But nothing happens and this error shows in the minibuffer. 
`(error "\"AttributeError(\\\"'ValueError' object has no attribute 'message'\\\",)\"").`

**Comment by syohex** [comment]
What is `arcsar.py` ? Can I get it from anywhere ?

**Comment by luluman** [comment]
It is a py file written by myself. It contain this:

```
import numpy as np
import matplotlib.pylab as pet
import matplotlib.font_manager as fm
from numpy import fft as ft
from mpl_toolkits.axes_grid1 import make_axes_locatable
fpath = '/Library/Fonts/Songti.ttc'
prop = fm.FontProperties(fname=fpath)

eps = np.finfo(float).eps

class test():
    def afun():
        a = np.arange(1,3)
        return a

def bfun():
    return True
```

**Comment by luluman** [comment]
It seems this code is the criminal 
`from mpl_toolkits.axes_grid1 import make_axes_locatable`

**Comment by luluman** [comment]
I just put `from mpl_toolkits.axes_grid1 import make_axes_locatable` in the class who needs it. Now jedi works fine. Although I don't know why it mess up everything. Thank you very much. @syohex  :+1:
