### ISSUE TITLE
not recognizing virtualenv?

### ISSUE THREAD

**Issue by vimsucks** [syohex/emacs-company-jedi#19]
I'm using virtualenvwrapper.el
After venv-workon a venv, it still attemping to complete the global site-packages, but not the packages in the virtualenv

related config:
```elisp
;;; Virtualenvwrapper:
(require 'virtualenvwrapper)
(venv-initialize-eshell)
(venv-initialize-interactive-shells)
(setq-default mode-line-format (cons '(:exec venv-current-name) mode-line-format))

;;; Company
(require 'company)
(add-hook 'after-init-hook 'global-company-mode)
(require 'company-jedi)
(setq company-show-numbers 1)
(setq company-minimum-prefix-length 2)
(require 'jedi-core)
(company-quickhelp-mode 1)
(add-hook 'python-mode-hook (lambda () (add-to-list 'company-backends 'company-jedi)))
(add-hook 'python-mode-hook 'jedi:setup)
(setq jedi:tooltip-method nil)
```

**Comment by syohex** [comment]
Could you remove `~/.emacs.d/.python-environments` and retry ?

**Comment by kuanyui** [comment]
I also has same problem. How to make company-jedi run under project's venv?

**Comment by syohex** [comment]
>  How to make company-jedi run under project's venv?

(Sorry I don't understand python programming well)

- Install jedi dependencies into project's venv
- Set emacs path environment/variable(python environment variable?) for project's venv. I suppose this can achieve by some packages(`pyvenv` , `virtualenvwrapper`?)
