### ISSUE TITLE
adding function call tips like in ''emacs-jedi"

### ISSUE THREAD

**Issue by oracleyue** [syohex/emacs-company-jedi#20]
Could you add the similar feature to `company-jedi`? Many thanks!
Like the following figure shows. 

You don't have to make it follow the cursor (actually it never works in my emacs, when still using auto-complete. No idea why.). Just show this function call signature in the mini-buffer when the cursor is in the parentheses after the function name. It is a small feature, but really useful. Now I have type `jedi:show-doc` to check the argument list. 
Or just tell me which function in the *jedi-core* gives this function call signature? then I could bind it to a key to see the signature. Thanks!

![8794015799_989e2a7217_o](https://cloud.githubusercontent.com/assets/5046605/22383906/39e6173e-e4cc-11e6-8379-499eb58b0b75.png)

**Comment by syohex** [comment]
> Or just tell me which function in the jedi-core gives this function call signature?

`jedi:get-in-function-call`
