### ISSUE TITLE
completion on point

### ISSUE THREAD

**Issue by 3246251196** [syohex/emacs-company-jedi#5]
When i complete on point I get the completions window, but for someone the completions window INCLUDES the period character at the beignning of all completion, which means I cannot continue to type and search!

How to not include the perioud character?

I deisalbe auto completion I like it to just be on a key press.

It looks like this:
![Uploading Untitled.png…]()

**Comment by syohex** [comment]
> It looks like this:
> [Uploading Untitled.png…]()

Image is not uploaded.

**Comment by syohex** [comment]
Could you tell me in more detail for reproducing this issue ?
- Did you use latest version ?
- How to reproduce ? steps ?
- configuration

Here is latest version animation GIF.

![company-jedi](https://cloud.githubusercontent.com/assets/554281/9400069/accdc6a2-47f7-11e5-91dd-d3e6037ece15.gif)

**Comment by 3246251196** [comment]
okay i needed to do this in jedi.el because i dont want ac:
[code]
;;;###autoload
(defun jedi:ac-setup ()
  "Add Jedi AC sources to `ac-sources'.

If auto-completion is all you need, you can call this function instead
of `jedi:setup', like this::

   (add-hook 'python-mode-hook 'jedi:ac-setup)

Note that this function calls `auto-complete-mode' if it is not
already enabled, for people who don't call `global-auto-complete-mode'
in their Emacs configuration.")

  ;; KKKKKKKK- I do not want to use this
  ;; (interactive)
  ;; (add-to-list 'ac-sources 'ac-source-jedi-direct)
  ;; (unless auto-complete-mode
  ;;   (auto-complete-mode)))
[/code]

.emacs:

[code]
;;;;;;;;;;;;;;;;
;; MODE : JEDI
(require 'jedi)
(autoload 'jedi:setup "jedi" nil t)
(require 'company-jedi)
[/code]
[code]
(setq company-backends '(company-c-headers
                         company-elisp
                         company-irony
                         company-jedi
                         company-capf
                         (company-dabbrev-code
                          company-gtags
                          company-etags
                          company-keywords)
                         company-files
                         company-dabbrev))
[/code]
[code]
(define-key global-map [f11] 'company-complete)
[/code]
[code]
(add-hook 'python-mode-hook 'jedi:setup)
(add-hook 'after-init-hook 'global-company-mode)
[/code]
[code]
;; IN THE CUSTOM-SET-VARIABVLES:
 '(jedi:environment-root nil)
 '(jedi:server-args nil)
[/code]

This entire configuration works on one machine but it causes peroblems on another. So, when I do something in pythoing olike:

1. someSymbol. 
2. Menu pops up
3. BUT, completions INCLUDE the . - i.e. the pattern ^\..*

So, like this:

Which means that if symbol has methoid called mymethod when after i do the . (and press F11) i cannot start typing the pattern ^mymethod because there is a \. in the pattern of candidates!

Like this:


![untitled](https://cloud.githubusercontent.com/assets/5910597/9406294/2253d2fa-47f7-11e5-91be-165f6db60e0b.png)

How do i get rid of the dot (this does not happen on other machine)

**Comment by syohex** [comment]
I can get results same as you with old version. But I cannot get with latest version. Please upgrade company-jedi version and try again.

**Comment by 3246251196** [comment]
Revision history for company-jedi.el

Revision 0.03 2015/06/24 syohex
   - Support many company-mode features, doc-buffer, annotation etc
     (Thanks Mario Rodas!!)
   - Update requirement version of jedi

Revision 0.02 2015/05/17 syohex
   - Update requirement version of jedi for showing document

Revision 0.01 2015/03/05 syohex
   - Initial release



------------------

;;; company-jedi.el --- company-mode completion back-end for Python JEDI -*- lexical-binding: t; -*-
;;
;; Copyright (C) 2009, 2011-2014  Free Software Foundation, Inc.

;; Author: Boy <boyw165@gmail.com>
;; Package-Requires: ((emacs "24") (cl-lib "0.5") (company "0.8.11") (jedi-core "0.2.5"))
;; Version: 0.03

;; This file is part of GNU Emacs.
;;
;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.
;;
;;
;;; Commentary:
;;  This is a company-backend for emacs-jedi. Add this backend to the
;;  `company-backends' and enjoy the power.
;;  e.g.
;;  ;; Basic usage.
;;  (add-to-list 'company-backends 'company-jedi)
;;  ;; Advanced usage.
;;  (add-to-list 'company-backends '(company-jedi company-files))
;;
;;  Check https://github.com/company-mode/company-mode for details.
;;
;;; Change Log:
;;  0.0.1
;;  - Initial release.
;;  - Get candidates through jedi.api.Script.completions().
;;  - 2 customizations to skip completion when point is in a string or comment.
;;
;;; Code:


---

The latest commit is in this version though.

I will have to try and collegues machine in a short while. my machine is fine and I am dead sure they are both the same version,

**Comment by syohex** [comment]
Do you use latest version really ? Latest version shows candidates type next to candidate(`[c]`,`[f]` etc). For example, `__class__[c]`.  However there are no candidate types in your screenshot. Please reinstall company-jedi and try again.(You might load old byte-compiled file.)

![company-jedi2](https://cloud.githubusercontent.com/assets/554281/9407133/8877b868-4841-11e5-97a9-f6d929fa2889.png)

**Comment by 3246251196** [comment]
Hi, yes, I can confirm the latest version fixes this. Thank you.
