### ISSUE TITLE
Documentation may be confusing for some users

### ISSUE THREAD

**Issue by jacktrades** [syohex/emacs-company-jedi#6]
I'm a newcomer to both `company-mode` and `jedi-mode`, so please excuse (and correct) any misunderstandings I may have here.  I was confused by the documentation for `company-jedi` that I found both in ELPA and in the readme here, and from a bit of searching on this issue, I think [others](https://github.com/tkf/emacs-jedi/issues/244) [are](https://www.reddit.com/r/Python/comments/3aosg1/emacs_jedi_disable_auto_complete_mode/) [too](http://stackoverflow.com/questions/29809061/how-to-properly-setup-jedi-with-elpy-in-emacs).

To me the description for the project read as if `company-jedi` should be installed **in addition to** `jedi` instead of **in lieu of** `jedi`.  I initially assumed that `company-jedi` was an extension that should be added to an existing install of the `jedi` package.  This obviously led to weird problems with both `autocomplete-mode` and `company-mode` competing for completion.

My first instinct was to just disable `autocomplete-mode` by `M-x autocomplete-mode` and that did solve the problem of `autocomplete-mode` stealing focus from `company-mode`.  After I noticed that, I did some investigation and discovered that I didn't need the `jedi` package at all.

A modification to the main description may be helpful  (if not some more detailed installation docs), perhaps something like:

> company-jedi is a replacement for the jedi package using company-mode for autocompletion instead of autocomplete-mode.

And maybe a warning in the readme:

> You can install company-jedi with the following command.
>     M-x package-install [RET] company-jedi [RET]
> Note: company-jedi is not compatible with the jedi package, you should only install one of the two.

**Comment by syohex** [comment]
See #7

**Comment by jacktrades** [comment]
LGTM, thanks for the quick response!  Hopefully this will save someone some debugging time.
